services:
  learning_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learning-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:password@database:27017
      - MONGODB_DB_NAME=learning_app_db
      - REDIS_URI=redis://redis_cache:6379
      - PORT=3000
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - database
      - redis_cache
    networks:
      - default

  # MongoDB service
  database:
    image: mongo:6-jammy
    container_name: database-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - default

  # Redis service
  redis_cache:
    image: redis:8.0-M02-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-config/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - default

  # RedisInsight for monitoring
  redis_monitor:
    image: redislabs/redisinsight:latest
    container_name: redis-monitor
    ports:
      - "5555:5540"
    environment:
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
    restart: unless-stopped
    networks:
      - default

volumes:
  mongo_data:
    name: mongo_data
    driver: local

networks:
  default:
    name: my-app-network
